export const PREFECTURES = [
  '全国（指定なし）',
  '北海道',
  '青森県', '岩手県', '宮城県', '秋田県', '山形県', '福島県',
  '茨城県', '栃木県', '群馬県', '埼玉県', '千葉県', '東京都', '神奈川県',
  '新潟県', '富山県', '石川県', '福井県', '山梨県', '長野県',
  '岐阜県', '静岡県', '愛知県', '三重県',
  '滋賀県', '京都府', '大阪府', '兵庫県', '奈良県', '和歌山県',
  '鳥取県', '島根県', '岡山県', '広島県', '山口県',
  '徳島県', '香川県', '愛媛県', '高知県',
  '福岡県', '佐賀県', '長崎県', '熊本県', '大分県', '宮崎県', '鹿児島県',
  '沖縄県'
];

export const INDUSTRIES = [
  '飲食・フードサービス業',
  '小売・卸売業・EC',
  '製造業・ものづくり・加工',
  '建設業・土木・リフォーム・設備工事',
  'IT・ソフトウェア・Webサービス',
  '宿泊・観光・旅行業',
  '生活関連サービス・理美容・クリーニング',
  '医療・歯科・福祉・介護・保育',
  '士業・専門コンサルティング・デザイン',
  '運輸・倉庫・物流・配送',
  '農業・林業・水産業',
  '不動産業・住宅',
  '教育・学習支援・スクール',
  '自動車整備・販売',
  'その他サービス業'
];

export const INVESTMENT_PURPOSES = [
  { id: 'it_dx', label: '💻 ITツール・ソフトウェア・業務DX（受発注・会計・予約・POS等）' },
  { id: 'equipment', label: '⚙️ 機械設備・専用機器・自動化ロボット・検査機器' },
  { id: 'marketing', label: '📣 販路開拓・HP制作・ECサイト・ネット広告・展示会出展' },
  { id: 'labor_saving', label: '🤖 カタログ型省力化機器（配膳ロボ、清掃機、券売機等）' },
  { id: 'wage_human', label: '👥 賃金引き上げ・非正規雇用者の正社員化・人材育成研修' },
  { id: 'energy_saving', label: '🌱 省エネ設備（高効率エアコン・LED・ボイラ・太陽光等）' },
  { id: 'renovation', label: '🏪 店舗改装・厨房設備・客席リニューアル・テイクアウト対応' },
  { id: 'new_business', label: '🚀 新事業進出・新商品開発・業態転換・海外展開' },
  { id: 'startup', label: '✨ 創業・新規開業・初期設備・オフィス家賃・運転資金' },
];

export const SAMPLE_PROFILES = [
  {
    title: '飲食店のセルフレジ・受発注DX & 賃上げ',
    badge: 'IT導入・業務改善',
    conditions: {
      region: '東京都',
      industry: '飲食・フードサービス業',
      purpose: '💻 ITツール・ソフトウェア・業務DX（受発注・会計・予約・POS等）',
      businessType: 'small_business' as const,
      employeeCount: '従業員4名（アルバイト含む）',
      capital: '300万円',
      investmentBudget: '約150万円',
      timing: '2〜3ヶ月以内',
      isWageIncreasePlanned: true,
      hasGBizId: true,
      freeTextDetail: 'ホールの人手不足解消のため、モバイルオーダー＆セルフレジを導入したい。時給を30円以上引き上げて賃金助成も狙いたい。',
    },
    message: '飲食店のホール人手不足解消のため、モバイルオーダーシステムとセルフレジの導入を検討しています。従業員の時給も引き上げる予定です。活用できる補助金や助成金を教えてください。',
  },
  {
    title: '製造業の最新CNC旋盤・AI外観検査機導入',
    badge: 'ものづくり補助金',
    conditions: {
      region: '愛知県',
      industry: '製造業・ものづくり・加工',
      purpose: '⚙️ 機械設備・専用機器・自動化ロボット・検査機器',
      businessType: 'medium_business' as const,
      employeeCount: '従業員18名',
      capital: '1,000万円',
      investmentBudget: '約2,500万円',
      timing: '半年以内',
      isWageIncreasePlanned: true,
      hasGBizId: true,
      freeTextDetail: '自動車部品の高精度加工のため、最新の5軸制御CNC旋盤とAI外観検査カメラを導入し、不良率の低減と生産能力2倍を目指す。',
    },
    message: '自動車部品の製造工場です。2,500万円ほどの最新5軸マシニングセンタとAI外観検査装置を導入して品質向上と生産性倍増を図りたいです。ものづくり補助金等の公募要件や採択のコツを提案してください。',
  },
  {
    title: '小規模サロンのチラシ・Web予約システムと店舗改装',
    badge: '持続化補助金',
    conditions: {
      region: '大阪府',
      industry: '生活関連サービス・理美容・クリーニング',
      purpose: '📣 販路開拓・HP制作・ECサイト・ネット広告・展示会出展',
      businessType: 'sole_proprietor' as const,
      employeeCount: '個人（従業員0名・代表のみ）',
      capital: '個人事業',
      investmentBudget: '約80万円',
      timing: '随時・すぐにでも',
      isWageIncreasePlanned: false,
      hasGBizId: false,
      freeTextDetail: '個人経営のエステ・ネイルサロンです。新規集客のためにホームページをリニューアルし、LINE連携のWEB予約システムとポスティングチラシを作成したい。',
    },
    message: '大阪で個人経営のプライベートサロンを開業して1年です。新規顧客開拓のため、WEB予約連携HPの作成とチラシ配布、看板設置で約80万円の投資を考えています。小規模事業者持続化補助金は使えますか？',
  },
  {
    title: '建設業の3D CAD・測量ドローン導入（2024年問題対応）',
    badge: '省力化・IT導入',
    conditions: {
      region: '福岡県',
      industry: '建設業・土木・リフォーム・設備工事',
      purpose: '🤖 カタログ型省力化機器（配膳ロボ、清掃機、券売機等）',
      businessType: 'small_business' as const,
      employeeCount: '従業員12名',
      capital: '500万円',
      investmentBudget: '約400万円',
      timing: '年内',
      isWageIncreasePlanned: true,
      hasGBizId: true,
      freeTextDetail: '残業時間規制（2024年問題）に対応するため、現場測量用ドローンと3D施工管理ソフトを導入し、現場測量・図面作成にかかる時間を半減させたい。',
    },
    message: '土木建設業です。現場の残業削減と人手不足解消のため、測量ドローンと3次元CAD施工管理システム（約400万円）を導入したいです。中小企業省力化投資補助金やIT導入補助金のどちらが向いていますか？',
  },
  {
    title: 'Web・IT企業の未経験エンジニア採用と正社員登用',
    badge: 'キャリアアップ・人材開発',
    conditions: {
      region: '全国（指定なし）',
      industry: 'IT・ソフトウェア・Webサービス',
      purpose: '👥 賃金引き上げ・非正規雇用者の正社員化・人材育成研修',
      businessType: 'small_business' as const,
      employeeCount: '従業員8名',
      capital: '300万円',
      investmentBudget: '約200万円（研修・処遇改善費）',
      timing: '随時',
      isWageIncreasePlanned: true,
      hasGBizId: false,
      freeTextDetail: '有期契約・契約社員で採用した未経験プログラマー3名を、半年間の社内外研修を経て正社員へ登用し、給与を5%以上昇給させたい。',
    },
    message: 'Web制作会社です。契約社員のエンジニア2〜3名を半年後に正社員化し、賃金を引き上げる予定です。厚生労働省のキャリアアップ助成金や人材開発支援助成金の活用法と注意点を詳しく教えてください。',
  }
];
